### PR TITLE
[#58] addressing the issue with non binary ids

### LINKED ISSUE #58: DELETE fails if the entity id type is integer

### PR DESCRIPTION
**Pull request by ferigis**
[close #58]

### CODE REVIEW

**Review by elbrujohalcon — APPROVED** [review]

File: src/sr_single_entity_handler.erl [hunk 1]
```diff
@@ -152,3 +155,19 @@ persist({ok, Entity}, Req1, State) ->
   ResBody = sr_json:encode(Module:to_json(PersistedEntity)),
   Req2 = cowboy_req:set_resp_body(ResBody, Req1),
   {true, Req2, State}.
+
+id_from_binding(binary, Id, _) ->
```
Comment (gadgetci) [inline src/sr_single_entity_handler.erl]: According to **Compiler**:
> Warning: missing specification for function id_from_binding/3
