### PR TITLE
[#43] state() types fixed

### LINKED ISSUE #43: Add "_=>_" to the state() types
add  "_ => _" to sr_entities_handler:state() and sr_single_entity_handle:state() types.

### PR DESCRIPTION
**Pull request by ferigis**
[close #43]

### CODE REVIEW

File: test/sr_basic_SUITE.erl [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+-export([types/1]).
+
+-spec all() -> [atom()].
+all() -> sr_test_utils:all(?MODULE).
+
+-spec types(sr_test_utils:config()) -> {comment, string()}.
+types(_Config) ->
+  ok = state1(#{any => value}),
+  ok = state2(#{any => value}),
+
```
Comment (elvisci) [inline test/sr_basic_SUITE.erl]: Line 13 has 2 trailing whitespace characters.

File: test/sr_basic_SUITE.erl [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+  {comment, ""}.
+
+-spec state1(sr_entities_handler:state()) -> ok.
+state1(_State) -> ok.
```
Comment (cabol) [inline test/sr_basic_SUITE.erl]: This test doesn't make sense to me, always return 'ok', no matter what it receives.

File: test/sr_basic_SUITE.erl [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+
+-spec state2(sr_single_entity_handler:state()) -> ok.
+state2(_State) -> ok.
```
Comment (cabol) [inline test/sr_basic_SUITE.erl]: Same previous comment
